function PluginPanel({scope}) {
 const e=React.createElement,snapshot=useFileConfig(scope);
 const [catalog,setCatalog]=React.useState(null),[editor,setEditor]=React.useState(null),[proposal,setProposal]=React.useState(null),[busy,setBusy]=React.useState(false),[error,setError]=React.useState(''),[notice,setNotice]=React.useState('');
 const alive=React.useRef(false),working=React.useRef(false),epoch=React.useRef(0),timer=React.useRef(null),serial=React.useRef(0);
 const reload=async()=>{const version=epoch.current,sequence=++serial.current,result=await scope.call('catalog',{});if(alive.current&&version===epoch.current&&sequence===serial.current){setCatalog(result);clearTimeout(timer.current);if(result.learning?.busy)timer.current=setTimeout(()=>{if(document.visibilityState!=='hidden')void reload().catch(reason=>{if(alive.current&&version===epoch.current)setError(reason.message);});},2000);}return result;};
 React.useEffect(()=>{alive.current=true;const version=++epoch.current;setCatalog(null);setEditor(null);setProposal(null);setError('');const refresh=()=>{clearTimeout(timer.current);if(document.visibilityState!=='hidden'&&snapshot.status==='ready'&&snapshot.value.enabled)void reload().catch(reason=>{if(alive.current&&version===epoch.current)setError(reason.message);});};refresh();window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{alive.current=false;++epoch.current;clearTimeout(timer.current);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[scope,snapshot.revision]);
 const work=async(fn)=>{if(working.current)return;const version=epoch.current;working.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(reason){if(alive.current&&version===epoch.current)setError(reason.message);}finally{working.current=false;if(alive.current)setBusy(false);}};
 const call=async(method,args)=>{const version=epoch.current,result=await scope.call(method,args);if(!alive.current||version!==epoch.current)return null;return result;};
 const open=async name=>{const result=await call('readSkill',{name});if(result)setEditor({...result.skill,originalName:result.skill.name});setProposal(null);};
 const submit=async(action,extra={})=>{const result=await call('propose',{request:{action,name:editor?.originalName,revision:editor?.revision??null,files:editor?.files,...extra}});if(result){setProposal(result);setEditor(null);await reload();}};
 const button=(label,onClick,variant='outline')=>e(DshButton,{type:'button',variant,disabled:busy||!snapshot.writable,onClick:()=>void work(onClick)},label);
 const draft=()=>{setEditor({originalName:null,revision:null,editable:true,files:{'SKILL.md':'---\nname: new-skill\ndescription: 填写何时使用这个技能\n---\n\n# 技能名称\n\n## 使用条件\n\n## 执行步骤\n\n## 验证结果\n'}});setProposal(null);};
 const display=value=>value===undefined?'（新文件）':typeof value==='string'?value:'（二进制资源 · '+Math.floor(value.base64.length*3/4)+' 字节，随技能包保留）';
 const review=async id=>{const result=await call('readProposal',{id});if(result)setProposal(result);setEditor(null);};
 return e('section',{className:'dpc-page workshop-panel','aria-label':'技能工坊'},
  e('style',null,'.workshop-panel{margin-bottom:32px}.workshop-toolbar{display:flex;gap:10px;flex-wrap:wrap}.workshop-skills{display:grid;gap:10px;margin:16px 0}.workshop-item{border:1px solid var(--dsw-alias-border-l2);border-radius:10px;padding:14px}.workshop-item h4{margin:0 0 6px}.workshop-item p{margin:6px 0;font-size:13px}.workshop-meta{font-size:12px;color:var(--dsw-alias-label-tertiary)}.workshop-editor textarea{box-sizing:border-box;width:100%;padding:12px;border-radius:10px;border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-2);color:inherit;font:13px/1.7 monospace;resize:vertical}.workshop-diff{display:grid;grid-template-columns:1fr 1fr;gap:12px}.workshop-diff pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:380px;overflow:auto;border:1px solid var(--dsw-alias-border-l2);padding:12px;font:12px/1.6 monospace;border-radius:8px}.workshop-panel code{overflow-wrap:anywhere}@media(max-width:620px){.workshop-diff{grid-template-columns:1fr}}'),
  e('div',{className:'workshop-toolbar'},button('新建技能',async()=>draft(),'primary'),button('从文件导入',async()=>{const filename=window.prompt('导入技能目录、SKILL.md、ZIP 或 .skill.json 的路径');if(!filename)return;const result=await call('importSkill',{request:{path:filename}});if(result)setProposal(result);await reload();}),button(catalog?.learning?.busy?'取消技能学习':'从最近会话学习',async()=>{await call(catalog?.learning?.busy?'cancelLearning':'startLearning',{});}),button('刷新列表',reload)),
  error?e('p',{role:'alert'},error):null,notice?e('p',{role:'status'},notice):null,
  !catalog?e('p',null,'正在读取原生技能…'):e(React.Fragment,null,
   catalog.complete===false?e('p',{role:'alert'},'部分技能来源暂不可用，以下显示已读取的技能。'):null,
   e('p',{className:'workshop-meta'},'当前工作区：',e('code',null,catalog.workspace)),
   e('p',{className:'workshop-meta'},'自动学习候选：',catalog.learning?.candidates??0,' / ',catalog.learning?.candidateLimit??32,' · 已管理技能：',catalog.managed?.length??0,' / ',catalog.learning?.managedLimit??64),
   catalog.recovery?.length?e('section',{'aria-label':'技能发布恢复'},e('p',{role:'alert'},'有发布尚未核对完成。遇到外部修改会保留现有文件与恢复目录；请处理冲突后重新核对。'),catalog.recovery.map(row=>e('p',{className:'workshop-meta',key:row.id},row.name+' · '+({prepared:'另一个进程正在发布',committed:'发布已提交，恢复目录待核对','needs-review':'需要审阅文件变化'}[row.state]??row.state),row.error?' · '+row.error:'',e('br'),e('code',null,row.recoveryDirectory))),button('重新核对恢复',async()=>{await call('recheckPublications',{});await reload();})):null,
   catalog.learning?.busy?e('p',{role:'status'},'正在从已完成的任务提炼技能，并按发布设置应用。'):null,
   catalog.learning?.reviews?.length?e('details',null,e('summary',null,'技能学习记录'),catalog.learning.reviews.map(row=>{const result=row.result?JSON.parse(row.result):{};return e('p',{className:'workshop-meta',key:row.session+':'+row.turn},new Date(row.created).toLocaleString()+' · '+(row.state==='completed'?(result.publication?.published?'已自动发布':result.publication?.reason==='awaiting-independent-evidence'?'自动验证中（无需人工确认）':result.publication?.reason==='managed-skill-limit'?'已达技能容量上限，暂缓发布':result.publication?.reason==='auto-publish-disabled'?'自动发布已关闭，保留待审':'已生成候选，待自动检查'):({running:'执行中',skipped:'没有可复用的新经验',cancelled:'已取消',failed:'失败',interrupted:'已中断'}[row.state]??row.state)),row.state==='failed'?' · '+result.error:'');})):null,
   e('div',{className:'workshop-skills'},catalog.skills.length?catalog.skills.map(skill=>e('article',{className:'workshop-item',key:skill.name},
    e('h4',null,skill.name),e('p',null,skill.description),e('p',{className:'workshop-meta'},skill.provider,' · ',skill.source,' · ',skill.invocation.modelInvocable?'模型可调用':'模型调用已关闭',' · ',skill.invocation.userInvocable?'用户可调用':'用户调用已关闭'),catalog.managed?.some(row=>row.name===skill.name)?e('p',{className:'workshop-meta'},'自动学习 · ',catalog.managed.find(row=>row.name===skill.name).uses,' 次使用'):null,button(skill.editable?'查看 / 编辑':'查看 / 复制',()=>open(skill.name))
   )):e('p',null,'还没有本地技能。新建或导入后，原生技能列表会自动更新。')),
   e('details',null,e('summary',null,'提案与发布记录'),catalog.proposals.map(item=>e('div',{className:'workshop-item',key:item.id},e('strong',null,item.name),e('span',{className:'workshop-meta'},' · ',{pending:'待审阅',publishing:'发布待核对','needs-review':'恢复需审阅',applied:'已发布',rejected:'已拒绝'}[item.state]??item.state),e('p',null,item.reason),button('查看差异',()=>review(item.id))))),
  ),
  editor?e('section',{className:'workshop-editor'},e('h4',null,editor.originalName||'新技能草稿'),e('textarea',{'aria-label':'SKILL.md 内容',rows:18,disabled:busy||!editor.editable,value:editor.files['SKILL.md'],onChange:event=>setEditor({...editor,files:{...editor.files,'SKILL.md':event.target.value}})}),
   Object.keys(editor.files).filter(name=>name!=='SKILL.md').length?e('details',null,e('summary',null,'技能资源（保存时一并保留）'),Object.entries(editor.files).filter(([name])=>name!=='SKILL.md').map(([name,value])=>e('details',{key:name},e('summary',null,name),typeof value==='string'?e('textarea',{'aria-label':name+' 内容',rows:8,disabled:busy||!editor.editable,value,onChange:event=>setEditor({...editor,files:{...editor.files,[name]:event.target.value}})}):e('p',null,display(value))))):null,
   e('div',{className:'dpc-actions'},editor.editable?button('生成待审提案',()=>submit('save'),'primary'):null,
    editor.originalName?button('复制',async()=>{const name=window.prompt('新技能名称');if(name)await submit('duplicate',{newName:name});}):null,
    editor.originalName&&editor.editable?button('重命名',async()=>{const name=window.prompt('新技能名称',editor.originalName);if(name)await submit('rename',{newName:name});}):null,
    editor.originalName&&editor.editable?button(editor.invocation.modelInvocable||editor.invocation.userInvocable?'停用技能':'启用技能',()=>submit(editor.invocation.modelInvocable||editor.invocation.userInvocable?'disable':'enable')):null,
    editor.originalName&&editor.editable?button('删除技能',()=>submit('delete')):null,
    button('导出技能包',async()=>{const data=JSON.stringify({format:'dsh-skill-bundle',version:1,files:editor.files},null,2),url=URL.createObjectURL(new Blob([data],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=(editor.originalName||'skill')+'.skill.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}),button('关闭编辑',async()=>setEditor(null))),
  ):null,
  proposal?e('section',{'aria-label':'技能提案差异'},e('h4',null,'审阅：'+proposal.name),e('p',null,proposal.action==='delete'?'确认后删除技能目录与其中的资源文件。':'校验通过；确认后写入原生技能目录。'),
   [...new Set([...Object.keys(proposal.before),...Object.keys(proposal.files)])].map(name=>e('details',{key:name,open:name==='SKILL.md'},e('summary',null,name,JSON.stringify(proposal.before[name])===JSON.stringify(proposal.files[name])?' · 无变化':' · 已修改'),e('div',{className:'workshop-diff'},e('div',null,e('small',null,'当前内容'),e('pre',null,display(proposal.before[name]))),e('div',null,e('small',null,proposal.action==='delete'?'删除后':'提案内容'),e('pre',null,proposal.action==='delete'?'（删除）':display(proposal.files[name])))))),
   e('div',{className:'dpc-actions'},proposal.state==='pending'?button(proposal.action==='delete'?'确认删除':'确认发布',async()=>{if(!window.confirm((proposal.action==='delete'?'删除技能及其资源：':'发布技能：')+proposal.name+'？'))return;await call('applyProposal',{id:proposal.id,confirmation:proposal.name});setProposal(null);setNotice('已发布，原生技能列表已更新。');await reload();},'primary'):null,proposal.state==='pending'?button('拒绝提案',async()=>{await call('rejectProposal',{id:proposal.id});setProposal(null);await reload();}):null,button('关闭审阅',async()=>setProposal(null))),
  ):null,
 );
}
